<a href="https://colab.research.google.com/github/smartsinovich/Stepik_NeuralNetworks_and_ComputerVision/blob/master/Stepik_seminar_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [0]:
a = torch.ones([5,4])
b = torch.Tensor([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16],
                  [17,18,19,20]])

In [0]:
a%b

tensor([[0., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [0]:
torch.zeros([3,4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [0]:
x = torch.ones([3,4,3])

In [0]:
x.size()

torch.Size([3, 4, 3])

In [0]:
x.shape

In [0]:
#вызов строки с номером i
x[0]
x[1]

In [0]:
x[0,0]

In [0]:
#вызов нулевого столбца, slice по всем элементам от 0 до конца
x[:,0]

In [0]:
x+10

In [0]:
#возведение в степень
x**2

In [0]:
#поэлементные арифметические операции
a+b
a*b
a/b
a%b

In [0]:
torch.exp(x)

In [0]:
torch.log(x)

In [0]:
torch.sin(x)

In [0]:
#маска: остаются элементы, удовлетворяющие условию
x[x>3]

In [0]:
#копирование ссылки (shallow): обе переменные ссылаются на один объект
y=x
y[0,0] = 999
print(x)
print(y)

In [0]:
#создание нового объекта - копия по значению
y=x.clone()
y[0,0] = 888
print(x)
print(y)

In [0]:
x.dtype

In [0]:
x = x.double()
print(x)
x = x.int()
print(x)
x = x.float()
print(x)

In [0]:
import numpy as np
x = np.array([[1,2,3,4],
              [4,3,2,1]])
x

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [0]:
#из numpy получаем tensor
x = torch.from_numpy(x)
x

tensor([[1, 2, 3, 4],
        [4, 3, 2, 1]])

In [0]:
#из tensor получаем numpy
x = x.numpy()

In [0]:
#random
x = torch.rand([2000,3000])
x

tensor([[0.1845, 0.5971, 0.5049,  ..., 0.0492, 0.7936, 0.0430],
        [0.1974, 0.0872, 0.2349,  ..., 0.6881, 0.7554, 0.2811],
        [0.7361, 0.9762, 0.4984,  ..., 0.6464, 0.1159, 0.8563],
        ...,
        [0.2722, 0.3830, 0.8647,  ..., 0.7030, 0.6551, 0.5900],
        [0.5988, 0.0290, 0.4659,  ..., 0.7065, 0.6044, 0.7984],
        [0.4518, 0.9190, 0.0893,  ..., 0.8232, 0.0243, 0.0375]])

In [0]:
torch.cuda.is_available()

True

In [0]:
#выбираем видеокарту, если их несколько (если одна - у нее номер 0)
torch.device('cuda:0')

device(type='cuda', index=0)

In [0]:
torch.device('cpu')

device(type='cpu')

In [0]:
#универсальный код: автоматический выбор
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda', index=0)

In [0]:
#перевод тензора на cuda
x_cuda = x.to(device)
x_cuda

tensor([[0.0159, 0.2520, 0.6176],
        [0.2323, 0.8999, 0.6760]], device='cuda:0')

In [0]:
#замеряем время рассчета на cpu
%time y = (x-x+x*10.0)**2

CPU times: user 19.9 ms, sys: 52.9 ms, total: 72.8 ms
Wall time: 77.1 ms


In [0]:
#замеряем время рассчета на gpu
%time y_cuda = (x_cuda - x_cuda + x_cuda * 10.0)**2

CPU times: user 1.14 ms, sys: 579 µs, total: 1.72 ms
Wall time: 1.92 ms
